### ISSUE TITLE
Create new Unleashed Tab

### ISSUE THREAD

**Issue by emilyJLin95** [trufflesuite/trufflesuite.com#1285]
We want to store our Unleashed content in a separate section. To do this:

- [x] Migrate the PetShop tutorial content into a guide underneath guides
- [x] Use mkdocs redirect so that the Petshop URL will redirect to the new guide
- [x] Instead of the tutorial tab, call it unleashed
- [x] Format it like how it is formatted underneath "blogs"
- [x] Add the first two episode guides (rentable-nft and nft-royalty)
- [ ] Use mkdocs redirect so that the original guide links redirect to the new location under the unleashed tab

**Comment by xhulz** [comment]
Hey @emilyJLin95,

The petshop has been added to the guide area.

I did not understand what I have to do about the last one item: `Use mkdocs redirect so that the original guide links redirect to the new location under the unleashed tab`. What I've seen, it's already working, right?

cc @kevinbluer 

Cheers
