### ISSUE TITLE
metamask incorrect nonce when using truffle develop testrpc

### ISSUE THREAD

**Issue by saneletm** [trufflesuite/trufflesuite.com#30]
I am trying to find the course for this issue. https://github.com/MetaMask/metamask-extension/issues/2373

I have a feeling it has to do with the accounts the truffle develop testrpc generates. 
It might have to do with  the fact that the Mnemonic: `candy maple cake sugar pudding cream honey rich smooth crumble sweet treat` is always used. Can this be randomized and changed per instance of the truffle develop testrpc.  I haven't looked at the code for the testrpc on truffle yet. this is just my higher level understanding after playing with it. I might be wrong, but would really appreciate some help.

**Comment by saneletm** [comment]
I will try to find and paste the exact error when I come across it online. its hard to copy it from metamask because it is just on a tooltip that appear when you hover your mouse over the "failed" string next to the transaction on metamask.

**Comment by bmmpxf** [comment]
Hi @saneletm . Thanks, we're definitely familiar with this issue. I've encountered it multiple times personally.

It's a tossup on whether it's a Truffle or MetaMask issue to be honest. MetaMask should be able to reset its network history when something has changed. Truffle Develop arguably should be able to change its mnemonic.

But I think the MetaMask team is going to beat us to the solution, as they have a fix in place for the network reset. See https://github.com/MetaMask/metamask-extension/issues/1999 . And since we have a workaround, having people use either Ganache (or [ganache-cli](https://github.com/trufflesuite/ganache-cli/), formerly known as the TestRPC) I think we're likely going to wait for MetaMask to update.

But I'll leave this ticket open for now at least until that happens. Thanks for the issue report!

**Comment by saneletm** [comment]
sounds good, thanks!

**Comment by bmmpxf** [comment]
Thanks for the update @eumend !
