### ISSUE TITLE
npm run dev endless browser reload

### ISSUE THREAD

**Issue by justinchou** [trufflesuite/trufflesuite.com#94]
when run `npm run dev` or just run `node dev.js`, the endless browser sync reload starts.

By change the config of browsersync will help.

```js
  files: [
    path.join(__dirname, './public/**/*'),
    path.join(__dirname, './renderers/**/*')
  ],
```

it exclude the 'build' folder generated by auto-build.

**Comment by DiscRiskandBisque** [comment]
Hi @justinchou , thank you for mentioning this! I'm not sure how no one ran into it earlier. I just switched to OS X and it popped up right away. 🤔 

Either way it's [fixed in the latest commit](https://github.com/trufflesuite/trufflesuite.com/commit/ce0ae09c1a13d3c1ea5b18dcd8c49c4341e80234). Thank you also for the PR, but the website structure has since changed so the files array needed different values.
